config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :items do
    resources :bids
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :images
  has_many :bids
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_many :bids
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:buyer, :seller, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :buyer
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery prepend: true
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :get_item
  before_action :set_bid, only: %i[ create show edit update destroy ]
  before_action :authenticate_user!

  # GET /bids or /bids.json
  def index
    @bids = @item.bids
  end

  # GET /bids/1 or /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    # @bid = Bid.new
    @bid = @item.bids.build
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids or /bids.json
  def create
    @bid = @item.bids.build(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to item_bids_path(@bid), notice: "Bid was successfully created." }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1 or /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to item_bids_path(@bid), notice: "Bid was successfully updated." }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1 or /bids/1.json
  def destroy
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to item_bids_path(@bid), notice: "Bid was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = @item.bids.find(params[:id])
      # @itemid = Item.find(params[:id])
      # @userid = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bid_params
      params.require(:bid).permit(:amount, :item_id, :user_id)
    end

    def get_item
      @item = Item.find(params[:item_id])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :starting_price, :current_bid, :end_time, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/bids/_bid.html.erb
<div id="<%= dom_id bid %>">
  <p>
    <strong>Amount:</strong>
    <%= bid.amount %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= bid.item_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= bid.user_id %>
  </p>

</div>

app/views/bids/_form.html.erb
<%= form_with(model: [@item, bid], local: true) do |form| %>
  <% if bid.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
        <% bid.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount, autofocus: true %>
  </div>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing bid</h1>

<%= render "form", bid: @bid %>

<br>

<div>
  <%= link_to "Show this bid", @bid %> |
  <%= link_to "Back to bids", bids_path %>
</div>

app/views/bids/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bids</h1>

<div id="bids">
  <% @bids.each do |bid| %>
    <%= render bid %>
  <% end %>
</div>

app/views/bids/new.html.erb
<h1>New bid</h1>

<%= render "form", bid: @bid %>

<br>

<div>

</div>

app/views/bids/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bid %>

<div>
  <%= link_to "Edit this bid", edit_bid_path(@bid) %> |
  <%= link_to "Back to bids", bids_path %>

  <%= button_to "Destroy this bid", @bid, method: :delete %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :starting_price, style: "display: block" %>
    <%= form.text_field :starting_price %>
  </div>

  <div>
    <%= form.label :current_bid, style: "display: block" %>
    <%= form.text_field :current_bid %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="list_item" id="<%= dom_id item %>">
 
<div class="listItem_thumb">
  
    <%= image_tag(item.images.first) %>
</div>

<div class="listItem_text">
   <h2>
      
        <%= link_to item.name, item %>
  </h2>
  

  <p>
     <%= item.description %>
  </p>

  <p>
    <strong>Starting price:</strong>
    <%= number_to_currency(item.starting_price, unit: "₹ " )%>
  </p>

  <p>
    <strong>Current bid:</strong>
    <%= number_to_currency(item.current_bid, unit: "₹ " ) %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= item.end_time %>
  </p>
</div>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<!-- <h1>Items</h1> -->

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="showitem_full">
  <div class="showitem_images" >
   <% @item.images.each do |image| %>
      <%= image_tag(image) %>
    <% end %>
</div>

<div class="showitem_desc">
  
  <h2><%= @item.name %></h2>

  <p>
     <%= @item.description %>
  </p>

  <p>
    <strong>Starting price:</strong>
    <%= number_to_currency(@item.starting_price, unit: "₹ " )%>
  </p>

  <p>
    <strong>Current bid:</strong>
    <%= number_to_currency(@item.current_bid, unit: "₹ " ) %>
    <%= link_to "Bid Now", new_item_bid_path(@item), class: "bidnow_btn" %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= @item.end_time %>
  </p>
</div>
</div>






<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  

  <!-- <%= button_to "Destroy this item", @item, method: :delete %> -->
</div>

<br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Antiques</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="content_wrapper">
      <header>
        <div class="site_branding">
          <h1><%= link_to "AntiquePlaza", root_path, class: 'logo_link' %></h1>
        </div>
        <div class="site_navbar">
        <nav>
            <%= link_to "Items", items_path %>
            <%= link_to "Add Item", new_item_path %>
        </nav>
        </div>
      </header>
   
    
    <main>
      <div class='main_wrapper'> 
         <div class="notices">
         <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>
       </div>
      <%= yield %>
      </div>
    </main>
    <footer>
      2023 - Copyrights Reserved @ AmulyaShahi 
    </footer>
    </div>
  </body>
</html>